Add method
Hiskynik/NikitaIvanov_LevelUp pull request #4
Opened 2023-02-14 18:15 UTC by Hiskynik

2023-03-01 19:53 UTC, khda91 requested changes
Исправить комментарии к работе

2023-03-01 19:53 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/IsHappy.java
> +            return false;
Почему тут возвращается `false`, а не ошибка выбрасывается?

2023-03-01 19:53 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/IsHappy.java
> +    public static void main(String[] arts) {
`main` метод не нужен

2023-03-01 19:53 UTC, khda91 commented on src/test/java/ru/levelp/at/homework2/IsHappyTest.java
> +        Assert.assertFalse(IsHappy.happy(1));
Тут лучше сделать реализацию через DataProvider

2023-03-02 08:17 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework2/IsHappyTest.java
> +        Assert.assertFalse(IsHappy.happy(1));
Да, я его сделал отдельным кодом, чтобы была видна разница в реализации. Вот ссылка на dataProvider в коммите: src/test/java/ru/levelp/at/homework2/dataprovider/IsHappyDataProviderTest.java

2023-03-02 19:27 UTC, Hiskynik commented on src/main/java/ru/levelp/at/homework2/IsHappy.java
> +            return false;
Обновил код, теперь возвращает ошибку.

2023-03-02 19:27 UTC, Hiskynik commented on src/main/java/ru/levelp/at/homework2/IsHappy.java
> +    public static void main(String[] arts) {
убрал метод main

2023-03-02 19:28 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework2/IsHappyTest.java
> +        Assert.assertFalse(IsHappy.happy(1));
добавил DataProvider в тест

2023-03-13 14:36 UTC, khda91 approved these changes
Работа принята

2023-03-30 21:22 UTC, merged