Ex. homework3
Hiskynik/NikitaIvanov_LevelUp pull request #5
Opened 2023-03-12 19:28 UTC by Hiskynik

2023-03-14 08:26 UTC, khda91 requested changes
Не обходимо исправить комментарии. 
Все ошибки типовые, по этому описал их только в одном классе. Для остальных брать из него

2023-03-14 08:26 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +class OpenMailDeleteMailTestIT {
Решил обойтись без базового класса?

2023-03-14 08:26 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +    public WebDriverWait wait;
А почему у переменной модификатор доступа `public`?

2023-03-14 08:26 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +   */
Браузер после теста не закрывается?

2023-03-14 08:26 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +        sleepUtils = new Thread();
А зачем нам тут `sleep`?

2023-03-14 08:26 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +        sleepUtils.sleep(3000);
Не должно быть thread.sleep в тестах

2023-03-14 08:26 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +        sleepUtils.sleep(3000);
Не должно быть thread.sleep в тестах

2023-03-15 21:21 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +    public WebDriverWait wait;
заменил на "protected"

2023-03-15 21:22 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +class OpenMailDeleteMailTestIT {
добавил базовый класс.

2023-03-15 21:24 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +   */
блок комментария забыл убрать. Поправил

2023-03-15 21:24 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +        sleepUtils = new Thread();
убрал sleep.

2023-03-15 21:26 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +        sleepUtils.sleep(3000);
заменил в тестах thread.sleep на явные ожидания.

2023-03-15 21:26 UTC, Hiskynik commented on src/test/java/ru/levelp/at/homework3/OpenMailDeleteMailTestIT.java
> +        sleepUtils.sleep(3000);
заменил в тестах thread.sleep на явные ожидания.

2023-04-03 09:32 UTC, khda91 approved these changes
Работа принята

2023-04-06 18:58 UTC, merged